version: '3.7'
services:
    mongodb:
        image: mongo:latest
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: rootpassword
            MONGO_INITDB_DATABASE: life-meet
        ports:
            - 27017:27017
        volumes:
            - mongodb_data_lifemeet_container:/data/db
        logging:
            driver: none
    redis:
        image: redis
        ports:
            - 6379:6379
        logging:
            driver: none

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.1.0
        environment: 
            - discovery.type=single-node
        container_name: elasticsearch
        ports: ['9200:9200']
    
    kibana:
        image: docker.elastic.co/kibana/kibana:7.1.0
        container_name: kibana
        ports: ['5601:5601']
        depends_on: ['elasticsearch']

volumes:
    mongodb_data_lifemeet_container:
