name: server
on:
  push:
    paths:
      - "server/**"
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: |
          cd server
          npm install
          tsc
          cp src/docs/swagger.yaml dist/docs/swagger.yaml
          zip -r server-ubuntu-20.4.zip .
      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: eu-west-1
      - name: Upload artifacts
        run: |
          cd server  
          aws s3 cp server-ubuntu-20.4.zip s3://life-meet-code-artifacts/server-ubuntu-20.4.zip --acl public-read
